### ISSUE TITLE
Add function to typeof tutorial

### ISSUE THREAD

**Issue by vkarpov15** [vkarpov15/masteringjs.io#32]
https://www.reddit.com/r/learnjavascript/comments/fae6th/the_typeof_operator_in_javascript_mastering_js/fixi4j3/?context=3&utm_medium=message_notification&utm_source=email&utm_name=892492742b82b269ac9b3eee47b2879b2d433253&utm_content=post_reply&utm_term=1

**Comment by IslandRhythms** [comment]
Done.
